site_name: SMART Health Cards Framework
nav:
  - Protocol: index.md
  - Credentials: credential-modeling.md
  - Vocabulary: vocabulary.md
  - Changelog: CHANGELOG.md

theme:
  name: material


plugins:
    - search
    - mermaid2

extra_javascript:
    - https://unpkg.com/mermaid/dist/mermaid.min.js
