site_name: SMART Health Cards Framework
repo_url: https://github.com/smart-on-fhir/health-cards
edit_uri: 'edit/main/docs'


nav:
  - Protocol: index.md
  - Credentials: credential-modeling.md
  - Vocabulary: vocabulary.md
  - Changelog: CHANGELOG.md

theme:
  name: material

markdown_extensions:
  - toc:
      permalink: True

plugins:
    - search
    - mermaid2

extra_javascript:
    - https://unpkg.com/mermaid/dist/mermaid.min.js
